spring.datasource.url=${voting.db.url:jdbc:h2:mem:test}
spring.datasource.username=${voting.db.username:sa}
spring.datasource.password=${voting.db.password:sa}
spring.datasource.driverClassName=${voting.db.driver:}
spring.datasource.platform=${voting.db.platform:h2}
spring.datasource.initialization-mode=always

server.servlet.context-path=/voting

logging.level.web=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.context=DEBUG

spring.jpa.hibernate.ddl-auto=${voting.ddl:create}
spring.jpa.show-sql=true

#properties for tuning @Retryable on controller
voting.get.backoff=250
voting.get.maxAttempts=5
voting.post.backoff=200
voting.post.maxAttempts=10